-- Sistema MEI — Contratos PHD (migrados das tabelas LOCAIS do MeiSistema.accdb:
-- modelocontrato e controlecontrato). Não existem na API Questor, por isso ficam no Supabase do Núcleo.
-- ADITIVA e idempotente. Os dados (5 modelos + 7 contratos) vão num arquivo separado,
-- fora do git (tem nome/CPF de clientes): _mei_dump/importar_contratos_mei.sql.

create table if not exists public.mei_contrato_modelo (
  codigo       integer generated by default as identity primary key,
  modelo       text not null,
  conteudo     text not null default '',          -- HTML com as variáveis @nomecliente, @valor1...
  ativo        boolean not null default true,
  criado_em    timestamptz not null default now(),
  criado_por   text,
  atualizado_em timestamptz,
  atualizado_por text
);

create table if not exists public.mei_contrato (
  codigo        integer generated by default as identity primary key,
  codigoempresa integer not null,                 -- controlecontrato.empresa
  codigoestab   integer not null default 1,       -- controlecontrato.filial
  codigosocio   integer,                          -- controlecontrato.socio
  modelo_codigo integer references public.mei_contrato_modelo(codigo),
  contrato      text not null,                    -- HTML já preenchido
  data_emissao  date,
  data_inicio   date,
  data_assinado date,                             -- preenchida = "Assinado"
  criado_em     timestamptz not null default now(),
  criado_por    text,
  atualizado_em timestamptz,
  atualizado_por text
);
create index if not exists mei_contrato_empresa_idx on public.mei_contrato (codigoempresa);

-- Mesmo padrão das outras tabelas do Núcleo acessadas só pelo servidor: RLS ligada, sem política
-- (só a service role, usada nas rotas /api/mei/contratos, lê e grava).
alter table public.mei_contrato_modelo enable row level security;
alter table public.mei_contrato enable row level security;
